### ISSUE TITLE
Connection reset error stops spark after some time?

### ISSUE THREAD

**Issue by rustyrussell** [shesek/spark-wallet#23] opened 2018-09-11 05:39 UTC
From my logs (stdout & stderr of spark).  This has happened several times.  spark-wallet --version == 0.1.1.

```
...
GET /stream?access-key=RAviKLwv5ZZBLUDngcBiagM7cLdPv923iSy6MdrVdus 200 25.565 ms - -
POST /rpc 200 13.431 ms - 411
uncaughtException, stopping process
Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TCP.onread (net.js:628:25)
```

**Comment by shesek** [comment] 2018-09-11 11:10
I believe 81fdabdd70b610dba14ee198785c2d5f3f6c8873 should fix this, can you try running from master and confirm?

```bash
$ git clone https://github.com/shesek/spark-wallet && cd spark-wallet && npm install && npm run dist:npm
$ ./dist/cli.js [args]
```

**Comment by sumBTC** [comment] 2018-09-11 13:29
I got the same error almost after the first or second payment.

GET /stream?access-key=S5f2ZBtPZ4UdGEuGZSvKaSDMyVltP236KPRTdqNGQ ^[[32m200 ^[[0m3.091 ms - -^[[0m
^[[0mGET /stream?access-key=S5f2ZBtPZ4UdGEuGZSvKaSDMyVltP236KPRTdqNGQ ^[[32m200 ^[[0m1.676 ms - -^[[0m
uncaughtException, stopping process
Error: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)

Did a "git pull" and "npm run dist:npm" and  the error didn't show up again after  a few payments..

**Comment by shesek** [comment] 2018-09-11 14:39
> almost immediately after the first or second payment:

 Is this after an incoming or an outgoing payment?

> Did a "git pull" and "npm run dist:npm" and the error didn't show up again after a few payments..

Thanks for checking this! Please report back if you're bumping into this error again.

**Comment by sumBTC** [comment] 2018-09-11 15:59
They were all outgoing payments, also the few that crashed it before the update. Did a few outgoing payments extra "a couple of hours ago" (as the wallet tells me). The wallet keeps running without any problems but I'll report back if it occurs again.

**Comment by sumBTC** [comment] 2018-09-12 17:02
I've had no problems sending payments, so I tried receiving a payment from coinpanic.com and Spark crashed:

    POST /rpc ^[[32m200 ^[[0m52.560 ms - -^[[0m
    POST /rpc ^[[32m200 ^[[0m17.866 ms - -^[[0m
    GET /stream?access-key=S5f2ZBtPZ4UdGEuGZSvKaSDMyVltP236KPRTdqNGQ ^[[32m200 1.382 ms - -
    POST /rpc ^[[32m200 ^[[0m152.606 ms - -
    GET /stream?access-key=S5f2ZBtPZ4UdGEuGZSvKaSDMyVltP236KPRTdqNGQ ^[[32m200 48.351 ms - -
    POST /rpc ^[[32m200 ^[[0m271.628 ms - -
    uncaughtException, stopping process
    Error: read ECONNRESET
        at _errnoException (util.js:992:11)
        at TCP.onread (net.js:618:25)

**Comment by darosior** [comment] 2018-09-22 12:14
Hi, maybe this information could help you : `nmap -Pn` the ip shuts down Spark every time with the same error.

**Comment by shesek** [comment] 2018-09-23 05:36
@darosior Thanks! That's very helpful, I am able to reproduce with that.

It looks like this is related to the changes introduced in https://github.com/shesek/spark-wallet/commit/62798caf243415d4194d5dc6b6e7bf388bb00d02. Removing the use of `createMultiServer` appears to fix the issue:

```diff
diff --git a/src/transport/tls.js b/src/transport/tls.js
index 3b8f1e5..874dc18 100644
--- a/src/transport/tls.js
+++ b/src/transport/tls.js
@@ -10,7 +11,8 @@ const defaultDir = path.join(require('os').homedir(), '.spark-wallet', 'tls')
 
 module.exports = (app, name=app.settings.host, dir=defaultDir, leEmail) => {
   const tlsOpt = leEmail ? letsencrypt(name, dir, leEmail) : selfsigned(name, dir)
       , redir  = (req, res) => (res.writeHead(301, { Location: `https://${ req.headers.host || name }/` }), res.end())
-      , server = createMultiServer(tlsOpt, app, redir)
+      , server = https.createServer(tlsOpt, app)
```

I knew from the beginning that `createMultiServer` is quite hacky and error-prone, and it has already caused issues previously (#10), so I think I'm just going to remove it. This means that users trying to access a TLS-enabled Spark server without using `https://` will receive an error, but I think that might be better than continuing to maintain this hack. :-\

**Comment by sumBTC** [comment] 2018-09-23 15:04
Not solved yet:

    Error: read ECONNRESET
        at _errnoException (util.js:992:11)
        at TCP.onread (net.js:618:25)

**Comment by shesek** [comment] 2018-09-25 08:02
Actually... it looks like `createMultiServer` is not to blame here. The cause is much simpler: the lower-level `net` module TCP server doesn't appear to handle `error` events by default (like the higher-level `http(s)` modules do), which causes any socket error to raise an uncaught exception and crash the process. These errors should be treated as warnings rather than being fatal.

The simple fix is to explicitly bind for `error` events, log them to `STDERR`, and let the process keep running. This was implemented in 56635b8af3fb54504e09d8a289b4e25b8d55e2e9. I will soon release v0.1.2 with this fix.

I guess `createMultiServer` gets to live another day. :)

**Comment by shesek** [comment] 2018-09-25 13:07
Released in v0.1.2. @darosior @sumBTC @rustyrussell could you please confirm this fixes it?

**Comment by sumBTC** [comment] 2018-09-25 18:28
My conclusion is that the issue has been solved. Tried all kinds of stuff and  sometimes I see a connection warning on the phone but the process on the server keeps going. Nice and thanks a lot!

**Comment by shesek** [comment] 2018-09-30 16:48
Alright, I'm closing this. Please report back if you're still experiencing crashes.

**Closed** 2018-09-30 16:48 UTC
Labels: bug
