### ISSUE TITLE
Android app v0.2.11 not able to make unencrypted connections

### ISSUE THREAD

**Issue by sumBTC** [shesek/spark-wallet#132] opened 2019-12-19 06:47 UTC
The moment the spark-wallet App on my android (version 9) phone updated to version 0.2.11, it was no longer able to connect to my server. Spark-wallet still worked in a browser. I went back to spark-wallet App version 0.2.9 and everything is working again. This has nothing to do with the latest version of c-lightning (0.8.0) which only requires one to run spark-wallet with `--ln-path ~/.lightning/bitcoin` on the server.

See also this closed [issue](https://github.com/shesek/spark-wallet/issues/128)

**Comment by shesek** [comment] 2019-12-19 12:12
Thanks for the report. I can't seem to reproduce this on my android, but I'll give this a try with a few more devices and report back.

Are you connecting via http, https or onion?

I recently [updated](https://github.com/shesek/spark-wallet/commit/933381ef1c9a4123868e23772394e6a61c089161) the android sdk target version from 27 to 28, perhaps this affected something? The [v0.2.11 apk](https://github.com/shesek/spark-wallet/releases/tag/v0.2.11) published on github releases should be identical to the one on the Play Store, except for still targeting sdk version 27 and not 28. Could you give this a try?

Also, I'm wondering if it might related [to this](https://www.theregister.co.uk/2019/12/16/chrome_79_update_a_catastrophe_for_android_users_wit_webview_apps/) by any chance?

**Comment by sumBTC** [comment] 2019-12-19 13:44
I run spark-wallet with `--no-tls` and in the App I connect via `http://myIP:9737` plus the access key. I installed the v0.2.11 apk  but that didn't help, still getting

**Comment by shesek** [comment] 2019-12-19 16:56
You definitely shouldn't be connecting over the public internet without using TLS or onion... :scream: Have you tried setting up an hidden service with `--onion`?

It appears like the issue definitely is related to targeting android sdk version 28. From ["An Update on Android TLS Adoption"](https://android-developers.googleblog.com/2019/12/an-update-on-android-tls-adoption.html):

> To ensure apps are safe, apps targeting Android 9 (API level 28) or higher automatically have a policy set by default that prevents unencrypted traffic for every domain. ... any use of unencrypted connections is the result of an explicit choice by the developer.

Looks like allowing unencrypted traffic now requires setting some explicit [network security configurations](https://developer.android.com/training/articles/security-config.html). I'll look into doing this with the Cordova build process that spark uses.

**Comment by shesek** [comment] 2019-12-19 17:09
Looks like this should do the trick: https://stackoverflow.com/a/56715421/865693

**Comment by sumBTC** [comment] 2019-12-19 19:02
> You definitely shouldn't be connecting over the public internet without using TLS

Well, [this](https://github.com/shesek/spark-wallet/issues/55) issue is still open.

> Have you tried setting up an hidden service with --onion?

As far as I understand it, I then need to run tor on my phone. That's a bit too much.

**Comment by shesek** [comment] 2019-12-20 01:02
Setting up Orbot on Android isn't too bad, I've been using it for quite some time on my device.

If you don't want to use Orbot and can't get the built-in TLS to work (I'm not sure why it doesn't for some people and wasn't able to reproduce this), I would still advise to look into some other solution for encryption - an nginx reverse proxy in front of the spark web server, ssh tunnel, vpn, or something similar.

Even though I don't recommend this, I'm working on a solution to allow making unencrypted connections. At the very least, its useful for development and testnet/regtest demonstrations. Will hopefully have something ready soon.

**Comment by k3tan172** [comment] 2019-12-20 01:21
Glad we've figured out the issue. Without the ```--no-tls``` flag, spark-wallet never worked for me either. I've connected over tor previously, it works, but as @sumBTC is saying, not keen on firing up orbot to access spark-wallet. My preferred method of access is through VPN.

**Comment by shesek** [comment] 2019-12-20 19:04
Reopening until @sumBTC / @k3tan172 confirms this works (will shortly be released as v0.2.12).

**Comment by shesek** [comment] 2019-12-22 16:54
I released v0.2.12, should shortly become available in the Play Store. @sumBTC @k3tan172 can you give this a go?

**Comment by sumBTC** [comment] 2019-12-22 17:59
Yes, `v0.2.12` works again with ` --no-tls` (but not without it). I installed it from the apk, not the Play Store. Well done and thanks!

**Comment by k3tan172** [comment] 2019-12-22 22:47
Can confirm, we're good here. Thanks for your help!

**Comment by shesek** [comment] 2019-12-23 01:02
Great! Thank you for confirming.

I do still recommend you to look into setting up something else to take care of encryption. You can try following the instructions [here](https://www.sitepoint.com/configuring-nginx-ssl-node-js/) to setup nginx as a reverse proxy with tls. If you're running into trouble, feel free to ping me on freenode (same nick) and I'll gladly help.

**Closed by shesek** 2019-12-23 01:02 UTC
