### ISSUE TITLE
Improve the UI for On-chain wallet/address

### ISSUE THREAD

**Issue by pavlenex** [shesek/spark-wallet#50] opened 2019-01-05 23:30 UTC
Right now [this is the way ](https://docs.btcpayserver.org/faq-and-common-issues/faq-lightningnetwork#how-to-find-an-on-chain-address-in-spark)to add the funds to on-chain spark wallet.
It's really complicated and not intuitive at all.
I see people on BTCPay Slack being confused about this on daily basis.
It would be really good if the UX there could improve.

**Comment by Klexx** [comment] 2019-01-06 01:52
related / duplicate of #49

**Comment by shesek** [comment] 2019-01-06 09:38
More like "create a UI" than "improve it". :) Having to use the "expert mode" and the RPC console to manually create addresses is definitely not ideal.

Integrating on-chain payments to the main "receive"/"pay" functionality (#49) is somewhat complicated, since c-lightning doesn't provide onchain transaction history and doesn't provide a way to get notifications about incoming onchain payments. Spark would have to implement its own onchain functionality and connect directly to bitcoind or some other data source. Hopefully at some point in the future, c-lightning could allow associating an onchain address with invoices and automatically track payments to it, which would make implementing onchain in Spark much easier.

However, I could definitely create a simple, separate UI just for getting onchain deposit addresses. But it wouldn't be able to tell the user that a payment has been received, which is kinda annoying (well, it could theoretically notify the user once the incoming payment is confirmed, by polling `listfunds` on an interval and diffing the `outputs` to identify new utxos, but I'm not sure its worth the complexity if it doesn't provide real-time feedback to the user's payment).

I'll look into this and see what I can do.

**Comment by shesek** [comment] 2019-02-17 08:16
> However, I could definitely create a simple, separate UI just for getting onchain deposit addresses.

Released in [v0.2.4](https://github.com/shesek/spark-wallet/releases/tag/v0.2.4)!

https://twitter.com/shesek/status/1097046906759495681

**Comment by shesek** [comment] 2019-02-17 08:17
Closing this, will keep #49 open to keep track of more advanced on-chain support, including sending to bitcoin addresses and integrating this with the main send/receive functionality.

**Closed by shesek** 2019-02-17 08:17 UTC
