### ISSUE TITLE
Usage of deprecated methods for current C-Lightning version

### ISSUE THREAD

**Issue by darosior** [shesek/spark-wallet#112] opened 2019-09-07 19:40 UTC
`listpayments` has been deprecated since `v0.7.0`, and as of `v0.7.3`, `listpayments` will be removed : https://github.com/ElementsProject/lightning/blob/master/CHANGELOG.md .

**Comment by shesek** [comment] 2019-09-08 00:43
This was already done: https://github.com/shesek/spark-wallet/commit/70d97a9841b5caadd36955304081430b2c45b6ee

But not released in a new version yet.

Are you aware of other deprecated APIs being used?

**Comment by darosior** [comment] 2019-09-08 10:01
No, I just experienced it with `listpayments` while running on master.

**Comment by shesek** [comment] 2019-09-08 15:27
I just double-checked to make sure, `listpayments` does not appear anywhere in the source code in the current master.

**Comment by darosior** [comment] 2019-09-10 19:08
Yeah it was marked as deprecated in 0.7.0 and has been removed in https://github.com/ElementsProject/lightning/pull/3004

**Comment by shesek** [comment] 2019-09-18 22:40
@leblitzdick Note that this change is in master, but not released in a version yet.

The latest spark release (v0.2.8) should work with the latest c-lightning (v0.7.2), unless you explicitly set set `allow-deprecated-apis` to `false`. The next spark release (v0.2.9) will work even with this configuration and on the next c-lightning release (v0.7.3).

Do you have `allow-deprecated-apis` disabled?

**Comment by leblitzdick** [comment] 2019-09-29 15:08
Ahh OK, so I must set "lightningd --allow-deprecated-apis true" then it works!
"lightningd" alone does not work. It must be set to TRUE manually no matter what the description says:

--allow-deprecated-apis <arg> Enable deprecated options...
                                                      (default: true)

**Comment by leblitzdick** [comment] 2019-09-29 15:58
No, I didn't, just start lightningd and by default its true.

**Comment by rustyrussell** [comment] 2019-09-30 05:34
It's been removed in c-lightning master.

@shesek You should always test against a c-lightning node with `allow-deprecated-apis=false` so you get 6 months heads-up on API breakage...

**Comment by shesek** [comment] 2019-10-10 19:32
@rustyrussell Yes, I am testing with `allow-deprecated-apis=false` and made the [necessary changes](https://github.com/shesek/spark-wallet/commit/70d97a9841b5caadd36955304081430b2c45b6ee) some time ago, but this still hasn't gotten released in a stable version of spark.

Is `allow-deprecated-apis` defaulting to `false` the expected behavior? I was under the impression that its set to true if not explicitly defined by the user.

**Comment by shesek** [comment] 2019-10-10 19:33
@darosior Sorry for the delay getting this released, I'll try to hurry this up!

**Comment by darosior** [comment] 2019-10-10 20:01
@shesek thanks!

**Comment by darosior** [comment] 2019-10-10 20:18
> Is allow-deprecated-apis defaulting to false the expected behavior? I was under the impression that its set to true if not explicitly defined by the user.

No you are totally right, guess it was a brainfart on my end :smile:.

**Comment by darosior** [comment] 2019-10-14 08:53
Do you think you'll be able to release before theLightningConference ? I don't think i'll be able to avoid making mobile ln payment there (and neither I think i'm the only spark wallet user going who runs an up-to-date C-lightning node).

**Comment by shesek** [comment] 2019-10-14 10:26
Wait, didn't you say that it is working with the most recent c-lightning version (v0.7.2) with the out-of-the-box configuration (no explicit `allow-deprecated-apis=false`)? Are you running into issues without modifying your `allow-deprecated-apis` option?

And yes, I believe I should be able to get this out (and possibly a couple more new features/improvements) before the lightning conference!

**Comment by darosior** [comment] 2019-10-14 11:43
> Wait, didn't you say that it is working with the most recent c-lightning version (v0.7.2) with the out-of-the-box configuration (no explicit allow-deprecated-apis=false)?

No. Actually it does not work with the latest C-lightning version (`0.7.3rc1`).

> Are you running into issues without modifying your allow-deprecated-apis option?

`listpayments` is no more an option, not even deprecated (it has been deprecated since `0.7.0` and removed in the latest release)

> Or are you running c-lightning from master?

I was when posting that issue, I'm now running the latest release.

> And yes, I believe I should be able to get this out (and possibly a couple more new features/improvements) before the lightning conference!

Great ! :-)

**Comment by shesek** [comment] 2019-10-14 23:52
> No. Actually it does not work with the latest C-lightning version (`0.7.3rc1`).

I was still considering the latest to be v0.7.2 because v0.7.3 is rc. But alright, I'll get on it. :)

**Comment by darosior** [comment] 2019-10-16 20:50
Ok so today being my last day at home before going to TheLightningConference, I could not wait more for the release (my node is self-hosted I won't be able to acces it after this evening) so I re-enabled `listpayments` as a `listsendpays` clone on `lightningd` to be able to use spark wallet at Berlin. If anyone is interested here is the branch with the patch https://github.com/darosior/lightning/tree/spark_compat (please note that this branch contains two commits not yet included into C-lightning master).

**Comment by shesek** [comment] 2019-10-17 05:00
[v0.2.9](https://github.com/shesek/spark-wallet/releases/tag/v0.2.9) is out, should become available in the Play Store within the next hour or so.

**Closed by shesek** 2019-10-17 05:00 UTC

**Comment by sumBTC** [comment] 2019-10-17 07:24
aaaaand it's working again (both web and app). Thanks!
